ecommerceproject/cart/urls.py
from django.urls import path,include
from . import views


app_name='cart'

urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('delete/<int:product_id>/', views.full_remove, name='full_remove'),

]

ecommerceproject/ecommerceproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include


from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('shop.urls')),
    path('search/',include('searchapp.urls')),
    path('cart/',include('cart.urls'))

]
if settings.DEBUG:
    urlpatterns += static (settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerceproject/searchapp/urls.py
from django.urls import path,include
from . import views

app_name='searchapp'
urlpatterns = [
    path('',views.searchresult,name='searchresult'),

]

ecommerceproject/shop/urls.py
from django.urls import path,include
from . import views
app_name='shop'
urlpatterns = [

    path('',views.allprodcat,name='allproductcat'),
    path('<slug:c_slug>/', views.allprodcat,name='productsbycategory'),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetail,name='prodcatdetail')


]

ecommerceproject/cart/models.py
from django.db import models
from shop.models import Product


# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format (self.cart_id)


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecommerceproject/searchapp/models.py
from django.db import models

# Create your models here.

ecommerceproject/shop/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('shop:productsbycategory',args=[self.slug])


    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)



    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('shop:prodcatdetail',args=[self.category.slug,self.slug])


    def __str__(self):
        return '{}'.format(self.name)

ecommerceproject/cart/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.


def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()        #session creation if not present
    return cart


def add_cart(request, product_id=None):
    product=Product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=_cart_id)
        cart.save()

    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
        cart_item.save()

    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(product=product,quantity=1,cart=cart)
        cart_item.save()

    return redirect('cart:cart_detail')


def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total +=(cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity

    except ObjectDoesNotExist:
        pass
    return render(request,"cart.html",dict(cart_items=cart_items,total=total,counter=counter))


def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()

    return redirect('cart:cart_detail')



def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()

    return redirect('cart:cart_detail')

ecommerceproject/searchapp/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
from django.http import HttpResponse


# Create your views here.

def searchresult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request, "search.html", {'query': query, 'products': products})

ecommerceproject/shop/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage


# Create your views here.


def allprodcat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        products_list=Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=Product.objects.all().filter(available=True)

    paginator=Paginator(products_list,6)         #paginator starts
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1

    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)      #paginator ends

    return render(request,"category.html",{'category':c_page,'product':products})


def proDetail(request,c_slug=None,product_slug=None,):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e


    return render(request,"product.html",{'product':product})

ecommerceproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet">
    <title>{% block title %} {% endblock %}</title>
    <script src="https://kit.fontawesome.com/c030210fca.js" crossorigin="anonymous"></script>
</head>
<body style="background-image:linear-gradient(Peru,wheat);">
<div class="container">
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>
</body>
</html>

ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    Cart-Kart.in,my cart
{% endblock %}
 Confirm your orders-
{% block title %}
  Confirm your orders-Cart- Kart.in
{% endblock %}

{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center" my-title> Nothing in Cart....Proceed to add something</h1>
        <p class="text-center">Goto<a href="{% url 'shop:allproductcat' %}">Home</a> add something and continue Shopping!!!</p>

    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title"><b>Your Kart</b></h1>
        <br>

    </div>
</div>

<div class="row mx-auto">
    <div class=" col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">
                    Your Items
                </th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="{{cart_item.product.get_absolute_url}}"><img src="{{cart_item.product.image.url}}" alt="prod img" class="float-left-rounded custom_image" width="100px" height="100px"></a>
                </td>
                <td class="text-lef">
                    {{cart_item.product.name}}
                    <br>
                     SKU: {{cart_item.product.id}}
                    <br>
                    Price: ${{cart_item.product.price}}
                    <br>
                    Qty: {{cart_item.quantity}} x {{cart_item}}
                </td>
                <td>
                    $ {{cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"> <i class="fa-solid fa-plus custom_a"></i> </a>&nbsp;
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"> <i class="fa-solid fa-minus custom_a "></i> </a>&nbsp;
                    <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"> <i class="fa-solid fa-trash custom_icon"></i></a>&nbsp;
                </td>
                {% else %}
                   <td>

                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"> <i class="fa-solid fa-minus custom_a "></i> </a>&nbsp;
                    <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"> <i class="fa-solid fa-trash custom_icon"></i></a>&nbsp;
                </td>
            </tr>
                {% endif %}
            {% endfor %}
            </tbody>

        </table>
    </div>
    <div class=" col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class=" table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th>
                    Checkout
                </th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        Please review cart items before proceeding with the order
                    </td>
                </tr>
            <tr>
                <td class="text-left">
                  <h2>  Your total is <strong>${{total}}</strong></h2>
                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'shop:allproductcat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
        </div>
    </div>
</div>


{% endif %}
{% endblock %}

ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {% if category %}
        {{category.description|truncatewords:155 }}
    {% else %]
        welcome to kart.in.........
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{category.name}}- Kart.in
        {% else %}
        See new products -kart.in
    {% endif %}
{% endblock %}


{% block content %}
    {% if category %}
<div>
    <div class="row my_row_class">
        <div class="mx-auto">
        <p><a class="mx-auto" href="{% url 'shop:allproductcat' %}">View all products</a></p><i class="fa-light fa-user-magnifying-glass"></i>
        </div>
    </div>
</div>
    {% endif %}
<div class="mx-auto">
    {% if category %}
    <center><img class="my_image" src="{{category.image.url}}" alt="{{category.name}}" width="800px" height="390px"></center>
</div>
    <br>
<div class="text-center my_title">
    <h1>{{category.name}}</h1>
    <p class="text-justify">{{category.description}}</p>
</div>
<div>
    {% else %}
    <br>
    <center><img class="my_image my_image_padding"  src="{% static 'img/banner.png' %}" alt="thanks" width="1300px" height="390px"></center>
</div>
<br>
<!--description-->
<div class="my_title">
    <h1 class="text-center my_title">
        <b>Products on sale!!</b>
    </h1>
    <p class="text-justify">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>

</div>
      {% endif %}

<div class="container">
    <div class="row mx_auto">
        {% for product in product.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4 ">
            <div class="shadow card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image"src="{{product.image.url}}" alt=" {{product.name}}-" width="300px" height="250px"></a><br>

            <div class="card-body">
                <h3>{{product.name}}</h3>
                <p>${{product.price}}</p>
            </div>
            </div>
        </div>

        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if product.paginator.num_pages > 1 %}

      <hr>
        <div class="text-center">
            {% for pg in product.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if product.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
          {% endif %}
    </div>
    <br>
</div>




{% endblock %}

ecommerceproject/templates/footer.html
<!--<div class="footer nav-bar-fixed-bottom my_footer">-->
<footer class="bg-light text-center text-lg-start">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color:sienna;">
    © 2023 Copyright:
    <a class="text-dark" href="#">Kart.in</a>  All rights reserved
  </div>
  <!-- Copyright -->
</footer>
<!--</div>-->

ecommerceproject/templates/header.html
{% load static %}
<header>
  <center>
    <a href="{% url 'shop:allproductcat' %}"><img src="{% static 'img/logo.jpg' %}" alt ="logo" width="100px" height="100px"></a>

  </center>
</header>

ecommerceproject/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
        <br><hr>
      </form>
    </div>
  </div>
</nav>

ecommerceproject/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <a class="navbar-brand" href="#"><i class="fa-solid fa-earth-asia"></i> Kart.in</a>
<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:allproductcat' %}">


<i class="fa-solid fa-house"></i><span class="sr-only"></span></a>
      </li>
      {% for cat in links %}
      <li> <a class="nav-link" href="{{cat.get_url}}">{{cat.name}}</a> </li>
      {% endfor %}

      <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
        <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Items
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'shop:allproductcat' %}">All Products</a>

          {% for cat in links %}
          <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>

          {% endfor %}

        </div>
      </li>
<!--      <li class="nav-item">-->
<!--        <a class="nav-link disabled" href="#">Disabled</a>-->
<!--      </li>-->
    </ul>
    <!--    <form class="form-inline ml-2 my-lg-0" style="text-align: center;">-->

    <form class="d-flex" action="{% url 'searchapp:searchresult' %}" method="GET">

      <input class="form-control me-2" type="search" placeholder="Search" name="q" id="q" aria-label="Search">
      <button class="btn btn-outline-success" type="submit"> <i class="fa-brands fa-searchengin"></i> </button>
    </form>
    <br><br>
<div class="col-1"></div>
    <div>
    <ul class="navbar-nav">
        {% if item_count > 0 %}
    <li class="nav-item">
     <center> <a class="btn btn-secondary" href="{% url 'cart:cart_detail' %}"><i class="fa-solid fa-cart-shopping"></i>({{item_count}})</a></center>

    </li>
        {% endif %}
    </ul>
    </div>
  </div>
  </div>
</nav>

ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}

        {{product.description|truncatewords:155 }}

{% endblock %}

{% block title %}
     {% if category %}
        {{product.name}}- Kart.in
    {% endif %}

{% endblock %}


{% block content %}

<div class="row my_prod_row_class">
  <div class="mx-auto">
    <p><a href="{% url 'shop:allproductcat' %}">Home</a>|<a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}} </p>
  </div>
</div>
<div class="container">

<br>
<div class="row">
  <div class=" col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <div style="min-width:18rem;">
      <img src="{{product.image.url}}"alt="{{product.name}}" width="500px" height="auto" style=" border: 3px solid #000; background:peru; margin: auto; padding: 15px 10px;">
        <br><br>
    </div>
  </div>
    <div class=" col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div class="my_title" id="h3ph">
            <h1><b>{{product.name}}</b></h1>
            <p>${{product.price}}</p>
            <p class="my_title">Product Description</p>
            <p class="text-justify my_prod_text">{{product.description}}</p>
            {% if product.stock <= 0 %}
            <p class="text-justify my_prod_text"><b>Out of Stock</b></p>
            {% else %}
            <a class="btn btn-secondary"href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
            <a class="btn btn-primary"href="#">Buy Now</a>
            {% endif %}
            <br>
        </div>
    </div>
</div>
</div>
{% endblock %}

ecommerceproject/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {{product.description|truncatewords:155 }}
{% endblock %}

{% block title %}
 <marquee>Search results-{{product.name}}- Kart.in</marquee>
{% endblock %}

{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for :<b><i>"{{query}}"</i></b></p>
</div>
<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4 ">
            <div class="shadow card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image"src="{{product.image.url}}" alt=" {{product.name}}-" width="300px" height="250px"></a><br>

            <div class="card-body">
                <h3>{{product.name}}</h3>
                <p>${{product.price}}</p>
            </div>
            </div>
        </div>
        {% empty %}
        <div>
            <h1 style="color:black;" class=" text-center my-title my_search_text">No Results Found!!!</h1>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}